---
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t alpine-logrotate .

      - name: Run the built image.
        run: docker run --name test-container -d --init alpine-logrotate

      - name: Verify logrotate is accessible in the built image.
        run: docker exec test-container logrotate --version
